PalletCity_Player_House_First_Floor_MapScripts::
	.byte 0

PalletCity_Player_House_FirstFloor_EventScript_Sign_101::
	msgbox PalletCity_Player_House_FirstFloor_Text_Sign_101, MSGBOX_SIGN
	end

PalletCity_Player_House_FirstFloor_EventScript_Sign_102::
	msgbox PalletCity_Player_House_FirstFloor_Text_Sign_102, MSGBOX_SIGN
	end

PalletCity_Player_House_FirstFloor_Text_Sign_101:
	.string "Apartment 101.$"

PalletCity_Player_House_FirstFloor_Text_Sign_102:
	.string "Apartment 102.$"
