PalletCity_Player_House_Entrance_MapScripts::
	.byte 0

PalletCity_Player_House_Entrance_EventScript_Sign_001::
	msgbox PalletCity_Player_House_Entrance_Text_Sign_001, MSGBOX_SIGN
	end

PalletCity_Player_House_Entrance_EventScript_Sign_002::
	msgbox PalletCity_Player_House_Entrance_Text_Sign_002, MSGBOX_SIGN
	end

PalletCity_Player_House_Entrance_Text_Sign_001:
	.string "Apartment 001.$"

PalletCity_Player_House_Entrance_Text_Sign_002:
	.string "Apartment 002.$"
