PalletCity_Player_House_Second_Floor_MapScripts::
	.byte 0
	
PalletCity_Player_House_SecondFloor_EventScript_Sign_201::
	msgbox PalletCity_Player_House_SecondFloor_Text_Sign_201, MSGBOX_SIGN
	end

PalletCity_Player_House_SecondFloor_EventScript_Sign_202::
	msgbox PalletCity_Player_House_SecondFloor_Text_Sign_202, MSGBOX_SIGN
	end

PalletCity_Player_House_SecondFloor_Text_Sign_201:
	.string "Apartment 201.$"

PalletCity_Player_House_SecondFloor_Text_Sign_202:
	.string "Apartment 202.$"
